name: Generate and Send Allure Report (ZIP)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-report:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest allure-pytest selenium webdriver-manager

      # Install Allure command-line tool
      - name: Install Allure
        run: |
          sudo apt-get update
          sudo apt-get install -y allure

      # Run tests and generate Allure results
      - name: Run tests
        run: |
          pytest test_script.py --alluredir=./allure-results

      # Generate Allure report
      - name: Generate Allure report
        run: |
          allure generate ./allure-results -o ./allure-report --clean

      # Compress the report folder into a ZIP
      - name: Compress Allure report
        run: |
          zip -r allure-report.zip ./allure-report

      # Upload the ZIP as an artifact (optional, for debugging)
      - name: Upload Allure report ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-zip
          path: allure-report.zip

      # Send email with the ZIP file
      - name: Send email with report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Allure Report - ZIP (Run ${{ github.run_number }})"
          to: your.manager@example.com  # Replace with your manager's email
          from: ${{ secrets.EMAIL_USERNAME }}
          body: "Please find the attached Allure report ZIP from the latest test run. Extract and open index.html in a browser."
          attachments: allure-report.zip